### ISSUE TITLE
Need to fix Games/My_Aquarium/wip.py, new version but some things are erroring.

### ISSUE THREAD

**Issue by 6100m** [WiiLink24/File-Maker#2]
So if I go through some cases in the script, such as
NOTE: This script does not currently generate objects in the tank
Would you like to add fish? [y/n] y
Would you like to use zero padding with the first ten Fish ID's? [y/n] y
Would you like to go into debug mode? [y/n] n
Since you aren't doing debug mode, do you want me to utilize the number 40 in the randomization process? [y/n] y
Processing ...

It will repeat for some reason.
Completed Successfully
Processing ...

Completed Successfully
Processing ...

Completed Successfully
Processing ...

Completed Successfully
Processing ...

Completed Successfully
Processing ...

Completed Successfully
Processing ...

Completed Successfully
Processing ...

Completed Successfully

Not to mention, sel SOMEHOW gets undefined in some places. @zurgeg Could you maybe take a look??

**Comment by zurgeg** [comment]
Okay, will take a look later.

**Comment by 6100m** [comment]
No worries zurgeg, I'll be fixing it :) I hope to show you my new shop ordering api when it's done :)

**Comment by 6100m** [comment]
Fixed.

**Comment by 6100m** [comment]
Software will be avaibile to download via Faux points, 50 of them to be exact.
